Add Python example
paytrail/api-documentation pull request #56
Opened 2022-10-25 10:10 UTC by NerdCloudDevsPT

## Related tickets & documents

* https://inoob.atlassian.net/browse/PP6-3

## Description

Add Python example code

2022-11-15 14:08 UTC, villev1 commented on docs/examples.md
> +  # create toDictionary() method to customize a convertter of object class to dict type
Typo here, convertter -> converter

2022-11-15 14:10 UTC, villev1 commented on docs/examples.md
> +# result after run the program:
This comment should probably be "running the program"

2022-11-15 14:15 UTC, villev1 commented on docs/examples.md
> +  def calculate_hmac(self, secret: str, hparams: dict, body: str='') -> str:
hparams could be more informative, headerParams or similar. Also in comment hparams -variable is camel case but in code it is lowercase

2022-11-15 14:22 UTC, villev1 commented on docs/examples.md
> +    # message must remove the whitespaces that were created during json parsing process
This a little weird comment as it says that message itself removes the whitespaces. Something like "whitespaces that were created during json parsing process must be removed" would make more sense.

2022-11-15 14:22 UTC, villev1 requested changes
Code looks good and works. Added few comments regarding style issues

2022-11-22 08:34 UTC, loueranta-paytrail approved these changes

2022-11-22 08:45 UTC, merged